# Generated by Django 5.1.7 on 2025-07-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infrastructure',
        ),
    ]
