# Generated by Django 5.1.7 on 2025-07-31 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visiteur',
        ),
    ]
